name = "profile-hutaobots"
main = "src/index.ts"
compatibility_date = "2026-08-03"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "KV"
id = "958e0894ae8543c4ae18084b5e75ae5e"
